# AppVeyor configuration file
# https://www.appveyor.com/docs/appveyor-yml

# Select build environment
# https://www.appveyor.com/docs/build-environment/
# https://www.appveyor.com/docs/windows-images-software/
# Note: Default is "Visual Studio 2015", which is Server 2012 R2, which is
# not supported by node 25.3.
image: Visual Studio 2022

# Be aware of https://github.com/nodejs/LTS when choosing versions to test
# Update engines.node in package.json if removing old versions.
environment:
  matrix:
    - nodejs_version: "20.19"
      # Empty version installs most recent version available
    - nodejs_version: ""

platform:
  # Uncomment to test on x86 (for packages with arch-dependent features)
  # - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  # Ignore package-lock.json.  This is done for a few reasons:
  # - To test against current versions of dependencies.
  # - To test installability for dependents (doesn't use package-lock.json).
  - if exist package-lock.json del package-lock.json
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

# Disable build step, which we don't need
build: off

# If any job fails, fail build immediately to avoid wasting time/resources.
matrix:
  fast_finish: true
